In [9]:
#for one feature
import numpy as np
def step_gradient(points,learning_rate,m,c):
    m_slope=0
    c_slope=0
    M=len(points)
    for i in range(M):
        x=points[i,0]
        y=points[i,1]
        m_slope+=(-2/M)*(y-m*x-c)*x
        c_slope+=(-2/M)*(y-m*x-c)
    new_m=m-learning_rate*m_slope
    new_c=c-learning_rate*c_slope
    return new_m,new_c
    
def cost(points,m,c):
    total_cost=0
    M=len(points)
    for i in range(M):
        x=points[i,0]
        y=points[i,1]
        total_cost+=(1/M)*((y-m*x-c)**2)
    return total_cost
def gd(points,learning_rate,num_iterations):
    m=0
    c=0
    for i in range(num_iterations):
        m,c=step_gradient(points,learning_rate,m,c)
        print("cost:",cost(points,m,c))
    return m,c
def run():
    data=np.loadtxt("C:/Users/Tarun Ahuja/Downloads/0000000000000836/data.csv",delimiter=",")
    learning_rate=0.0001
    num_iterations=100
    m,c=gd(data,learning_rate,num_iterations)
    print(m,c)
    
run()

cost: 1484.5865574086486
cost: 457.8542575737672
cost: 199.5099857255389
cost: 134.50591058200533
cost: 118.1496934223995
cost: 114.0341490603815
cost: 112.99857731713657
cost: 112.73798187568467
cost: 112.6723843590911
cost: 112.65585181499745
cost: 112.65166489759581
cost: 112.6505843615011
cost: 112.65028544701502
cost: 112.65018320293967
cost: 112.650130445072
cost: 112.65009013922885
cost: 112.6500529669463
cost: 112.65001658353178
cost: 112.64998039901865
cost: 112.64994426496071
cost: 112.64990814400622
cost: 112.64987202675677
cost: 112.64983591084761
cost: 112.64979979568368
cost: 112.64976368111523
cost: 112.64972756710469
cost: 112.64969145364236
cost: 112.64965534072611
cost: 112.64961922835512
cost: 112.64958311652944
cost: 112.64954700524868
cost: 112.64951089451318
cost: 112.64947478432279
cost: 112.64943867467744
cost: 112.64940256557728
cost: 112.64936645702221
cost: 112.64933034901203
cost: 112.64929424154704
cost: 112.64925813462712
cost: 112.6492220282522
cost: 112.

In [16]:
import pandas as pd

s1 = pd.Series([40,10,70,100,40], index=(range(5)))
s2 = pd.Series([10, 9, 8, 7, 6, 5], index=(range(6)))
df = pd.DataFrame(s1, columns=['s1'])
df['s2'] = s2
df

from mlxtend.preprocessing import minmax_scaling

minmax_scaling(df, columns=['s1'])

s1
0  0.333333
1  0.000000
2  0.666667
3  1.000000
4  0.333333

In [20]:
from sklearn import preprocessing
x=np.array([[1.,-1.,2.],
            [2.,0.,0.],
            [0.,1.,-1.]])
x_scaled=preprocessing.scale(x)

In [22]:
x_scaled.mean(axis=0)

array([0., 0., 0.])

In [24]:
x_scaled.std(axis=0)

array([1., 1., 1.])

In [26]:
x_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [28]:
scaler=preprocessing.StandardScaler()
scaler.fit(x)

scaler.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [30]:
x_test=[[1,1,0]]
scaler.transform(x_test)

array([[ 0.        ,  1.22474487, -0.26726124]])

In [81]:
import numpy as np
def step_grad(points, learn_rate, M):
    N = points.shape[0]
    num_col = points.shape[1]
    
    new_M = np.zeros(num_col)
    
    for i in range(N):
        x = points[i, 0:num_col-1]
        x = np.append(x, 1)
        y = points[i, num_col-1]
        for j in range(num_col):
            new_M[j] += (-2/N) * (y - (M * x).sum()) * x[j]
        M = M - (learn_rate * new_M)
    
    return M
def gd(points, learn_rate, num_iter):
    num_col = points.shape[1]
    M = np.zeros(num_col)
    
    for i in range(num_iter):
        M = step_grad(points, learn_rate, M)
        if i % 100== 0:
            print(i, "Cost= ", cost(points, M))
    print(i, "Cost= ", cost(points, M))
    return M

def cost(points, M):
    total_cost = 0
    
    N = points.shape[0]
    num_col = points.shape[1]
    
    for i in range(N):
        x = points[i,0:num_col-1]
        x = np.append(x, 1)
        y = points[i,num_col-1]
        total_cost += (y - (M * x).sum()) ** 2
        
    total_cost = (1/N) * total_cost
    return total_cost

def run():
    data=np.loadtxt("C:/Users/Tarun Ahuja/Downloads/0000000000002417_training_boston_x_y_train (1).csv",delimiter=",")
    r=np.ones(len(data))
    u=data[:,13]
    data=np.concatenate((data[:,0:13], r.reshape(len(data),1)), axis=1)
    data=np.concatenate((data,u.reshape(379,1)),axis=1)
    learning_rate=0.0001
    num_iterations=1000
    m=gd(data,learning_rate,num_iterations)
    print(m)
    
run()

0 Cost=  511.5632190154138
100 Cost=  24.93502807474201
200 Cost=  24.11394239655515
300 Cost=  23.87992887167038
400 Cost=  23.782580145193783
500 Cost=  23.730397060623677
600 Cost=  23.697983386913787
700 Cost=  23.676188960997706
800 Cost=  23.660860460135563
900 Cost=  23.649765760196107
999 Cost=  23.641640754710117
[-1.04831141  0.61114343 -0.51210121  0.68196129 -1.89781988  2.48129984
 -0.10277248 -2.90155579  2.07722064 -1.20863008 -2.05762568  0.59499583
 -4.00869049 11.32401544 11.32401544]


In [76]:
data=np.loadtxt("C:/Users/Tarun Ahuja/Downloads/0000000000002417_training_boston_x_y_train (1).csv",delimiter=",")

r=np.ones(len(data))
u=data[:,13]
data=np.concatenate((data[:,0:13], r.reshape(len(data),1)), axis=1)
data=np.concatenate((data,u.reshape(379,1)),axis=1)
data

array([[-0.40784991, -0.48772236, -1.2660231 , ..., -1.09799011,
         1.        , 37.9       ],
       [-0.40737368, -0.48772236,  0.24705682, ..., -0.52047412,
         1.        , 21.4       ],
       [ 0.1251786 , -0.48772236,  1.01599907, ...,  0.89107588,
         1.        , 12.7       ],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ..., -0.33404299,
         1.        , 20.8       ],
       [-0.41061997, -0.48772236, -1.15221381, ..., -0.74475218,
         1.        , 22.6       ],
       [ 0.34290895, -0.48772236,  1.01599907, ..., -1.35871335,
         1.        , 50.        ]])