In [ ]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0], [2,0], [2,1],
               [4, 2], [4, 4], [4, 0], [5,0], [5,1]])
Y= np.array([[0]])
print(X)
kmeans = KMeans(n_clusters=2,random_state=0).fit(X,Y)
kmeans.labels_



In [147]:
import ogr
import random
from osgeo import gdal
import glob
import os
import gdal
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from scipy.ndimage import gaussian_filter1d
from scipy import signal

driver = gdal.GetDriverByName('GTiff')
filename = r"C:\Users\Tarun Ahuja\Downloads\final_mask.tif" #path to raster
dataset = gdal.Open(filename)
band = dataset.GetRasterBand(1)
cols = dataset.RasterXSize
rows = dataset.RasterYSize
transform = dataset.GetGeoTransform()
xOrigin = transform[0]
yOrigin = transform[3]
pixelWidth = transform[1]
pixelHeight =-transform[5]
datamask = band.ReadAsArray(0, 0, cols, rows)

gimms_folder = r'C:\Users\Tarun Ahuja\Downloads\2013-14\2013-14'
gimms_files = sorted(glob.glob(gimms_folder+'/*.tif'))
num = len(gimms_files)
m=[]
y=[]
a=[]
for z in range(1400):
    with open(r'outputs.txt', 'r') as myfile:
        data = myfile.readlines()
    #print(data[z])
    ndvi=[]
    j=[]
    
    t=data[z].split()
    lats=float(t[0])
    long=float(t[1])
    crops=float(t[2])
    points_list=[(lats,long)]
    for point in points_list:
        col = int((point[1] - xOrigin) / pixelWidth)
        row = int((yOrigin - point[0] ) / pixelHeight)
    #print(row,col, datamask[row][col])
  
    y.append([int(crops)])
    b = 0
    for eachfile in gimms_files:
        ds = gdal.Open(eachfile)
        band = ds.GetRasterBand(1)
        NoDataValue = band.GetNoDataValue()
        
        ndvi.extend(*band.ReadAsArray(row,col,1,1))
        j.append(ndvi)
        #m.append(ndvi)
        b+=1
    #t=np.array(ndvi)
    ndvi = np.array(ndvi)
    a.insert(z,ndvi)
print(*a[1])
#print(y)
'''
x=[]
x=T_S()
t=np.array(x)
print(x)
list1=[]
list1.append(x)
print(list1)
'''

345.0 485.0 715.0 715.0 740.0 700.0 610.0 495.0 395.0 330.0 315.0 430.0 545.0 635.0 715.0 750.0 735.0 670.0 565.0 435.0 315.0 225.0 200.0 260.0


'\nx=[]\nx=T_S()\nt=np.array(x)\nprint(x)\nlist1=[]\nlist1.append(x)\nprint(list1)\n'

In [148]:
print(a[0],sep=", ")
#j=np.array(a)
s=np.array(a)

print(np.array(y))

[465. 595. 675. 730. 715. 660. 590. 510. 435. 390. 390. 530. 675. 775.
 845. 860. 810. 705. 565. 420. 305. 240. 235. 300.]
[[  2]
 [  2]
 [  2]
 ...
 [  2]
 [-99]
 [  2]]


In [15]:
from sklearn.cluster import KMeans
import numpy as np
X = s
Y= np.array(y)

kmeans = KMeans(n_clusters=4,random_state=1).fit(X,Y)
# kmeans.labels_
kmeans.predict([[345.0, 485.0, 715.0, 715.0, 740.0, 700.0, 610.0, 495.0, 395.0 ,330.0, 315.0, 430.0, 545.0, 635.0, 715.0, 750.0 ,735.0, 670.0, 565.0, 435.0, 315.0, 225.0 ,200.0, 260.0,
]])

array([0])

In [222]:
kmeans.labels_[1:1000]

array([0, 0, 2, 3, 3, 0, 1, 1, 0, 0, 0, 3, 1, 2, 2, 0, 1, 0, 2, 2, 0, 0,
       3, 0, 1, 1, 1, 0, 0, 3, 3, 3, 1, 1, 0, 2, 3, 3, 0, 3, 2, 1, 1, 1,
       1, 1, 3, 0, 2, 0, 1, 1, 3, 1, 2, 1, 3, 0, 1, 3, 2, 1, 2, 0, 0, 0,
       0, 0, 1, 3, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 2, 0, 0, 0, 2, 3, 1, 0, 0, 3, 0, 3, 2, 3, 3, 1, 3, 1, 0, 1,
       0, 0, 3, 0, 1, 0, 0, 0, 3, 0, 3, 0, 1, 0, 1, 1, 1, 0, 3, 2, 0, 0,
       3, 0, 0, 0, 0, 2, 2, 2, 3, 1, 1, 0, 2, 2, 1, 1, 2, 2, 2, 3, 0, 2,
       3, 0, 0, 3, 3, 1, 1, 1, 2, 2, 2, 1, 3, 0, 0, 3, 0, 3, 3, 1, 2, 1,
       0, 3, 0, 3, 0, 3, 3, 1, 0, 2, 1, 1, 3, 1, 3, 1, 3, 1, 3, 0, 1, 1,
       1, 2, 2, 2, 3, 3, 0, 1, 1, 3, 3, 2, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 3, 0, 2, 3, 3, 0, 1, 0, 2, 1, 2, 1, 0, 1, 0, 0, 2, 3,
       3, 3, 3, 1, 1, 2, 3, 0, 0, 0, 2, 2, 0, 1, 2, 3, 0, 2, 3, 3, 0, 0,
       0, 1, 0, 0, 2, 2, 1, 0, 2, 0, 1, 1, 0, 1, 0, 2, 3, 0, 3, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 2, 0, 0, 2, 3, 3, 2, 0, 3,

In [223]:
kmeans.cluster_centers_


array([[ 4.1195691e+02,  5.4711206e+02,  7.3689423e+02,  7.3803064e+02,
         7.4303497e+02,  6.8537512e+02,  5.8760199e+02,  4.8401941e+02,
         4.0922748e+02,  3.8682516e+02,  4.2325818e+02,  5.5283203e+02,
         6.8233228e+02,  7.5329388e+02,  7.8916003e+02,  7.8146143e+02,
         7.4352594e+02,  6.7960645e+02,  5.9184113e+02,  4.7773450e+02,
         3.6432452e+02,  2.7137030e+02,  2.3107182e+02,  2.6764630e+02],
       [ 2.0619299e+02,  2.1645956e+02,  3.9149756e+02,  3.8835013e+02,
         3.9903583e+02,  3.4949200e+02,  3.2213177e+02,  2.8753799e+02,
         2.4733492e+02,  2.5242380e+02,  2.4961935e+02,  2.4880753e+02,
         2.4797015e+02,  2.4946690e+02,  2.4170103e+02,  2.5228345e+02,
         2.4880753e+02,  2.3180180e+02,  2.0696712e+02,  2.0140839e+02,
         2.0546959e+02,  1.9786806e+02,  1.9963187e+02,  2.0703040e+02],
       [-6.5612793e-04,  1.0070801e-03,  6.1035156e-05,  1.2817383e-03,
        -9.4604492e-04, -1.4343262e-03,  5.4931641e-04,  1.770

In [146]:
yt=[]
at=[]

for zt in range(1401,2007):
    with open(r'outputs.txt', 'r') as myfile:
        data = myfile.readlines()
    #print(data[z])
    ndvit=[]
    jt=[]
    
    tt=data[zt].split()
    latst=float(tt[0])
    longt=float(tt[1])
    cropst=float(tt[2])
    points_listt=[(latst,longt)]
    for pointt in points_listt:
        colt = int((pointt[1] - xOrigin) / pixelWidth)
        rowt = int((yOrigin - pointt[0] ) / pixelHeight)
    #print(row,col, datamask[row][col])
  
    yt.append([int(cropst)])
    bt = 0
    for eachfilet in gimms_files:
        dst = gdal.Open(eachfilet)
        bandt = dst.GetRasterBand(1)
        NoDataValuet = bandt.GetNoDataValue()
        
        ndvit.extend(*bandt.ReadAsArray(rowt,colt,1,1))
        jt.append(ndvit)
        #m.append(ndvi)
        bt+=1
    #t=np.array(ndvi)
    ndvit = np.array(ndvit)
    at.insert(zt,ndvit)
print(*at[1])


190.0 220.0 365.0 380.0 395.0 325.0 275.0 270.0 235.0 265.0 235.0 220.0 210.0 210.0 200.0 210.0 205.0 180.0 180.0 195.0 175.0 170.0 180.0 180.0


In [149]:
from sklearn import svm
M=np.array(at)
N=np.array(yt)

X = s
Y = np.array(y)
clf = svm.SVC(gamma='auto')
clf.fit(X, Y)
clf.score(M,N)


C:\Users\Tarun Ahuja\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7937293729372937

In [120]:
print(*at[0])

200.0 170.0 315.0 315.0 355.0 275.0 290.0 270.0 235.0 250.0 220.0 220.0 215.0 215.0 195.0 200.0 190.0 195.0 175.0 190.0 180.0 180.0 200.0 235.0
